name: Keepalive Workflow
on:
  schedule:
    - cron: '0 0 1 * *' # Runs at 00:00 on the 1st of every month
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          commit_message: "chore: auto-keepalive to prevent workflow suspension"
